### ISSUE TITLE
How to configure discovery to add instance's interface IP per host instead of 127.0.0.1?

### ISSUE THREAD

**Issue by valery-zhurbenko** [ike-dai/zaws#2]
for now all aws EC2 hosts added, but each instance in zabbix have interface IP 127.0.0.1. This is greyed and not editable because added by discovery rule from template.
My EC2 instances have hostname that is "APPNAME_INSTANCEID", like "web1_i-01013167c8f712345". So I changed "host prototype" in rule to:
{#INSTANCE.NAME}_{#INSTANCE.ID}

Now all added, but problem to allow agents to be accepted, probably because this registered in zabbix host names have different interface IP (127.0.0.1) then real host IP. Same issue if host added by agent - discovery rule can do nothing because this name exists....

The goal is to manage instance lifecycle (adding and removing) and AWS resources with zaws discovery, but be able to monitor with installed there agent.

How to define discovery to add real instance IP instead of 127.0.0.1?

Thanks!

**Comment by ike-dai** [comment]
This is becouse of Zabbix specification.
By this specification, each interfaces are set the parent host interface information automatically.
If you want to monitor Zabbix Agent type data, please change the item type to "Zabbix Agent(Active)".
By this way, Zabbix Server doesn't need to know each Agent interface information.
At this type, the following point is important.

 * host name must equal Hostname in zabbix_agentd.conf.

Please check it.

If you want to set interface info absolutely, please consider the other tool.

 Zabbix AWS monitoring templates: https://github.com/tech-sketch/zabbix_aws_template

This template includes auto registration hosts scripts for AWS auto scaling.
This script doesn't use Zabbix low-level-discovery func, but it use Zabbix API.
So, it regist to host interface public or private IP of EC2 instance.
