### ISSUE TITLE
Agent interfaces on AWS discovered hosts

### ISSUE THREAD

**Issue by fhperuchi** [ike-dai/zaws#3]
Hi @ike-dai !

Is it possivel to add **Agent interfaces** on AWS discovered hosts? I want to a Agent interface pointing to the public IP address of my AWS instance on port 10050 to collect data from the **Zabbix agent** installed on the instance.

![image](https://cloud.githubusercontent.com/assets/4641123/25757749/298545ae-31a2-11e7-9aa2-6062a7d90f31.png)

Thank you a lot for this resource.

**Comment by ike-dai** [comment]
Sorry for late reply.
Because of the limit of Zabbix specification, LLD host prototype is fixed in the parent host interface..
This issue is discussed in https://support.zabbix.com/browse/ZBXNEXT-2088 and https://support.zabbix.com/browse/ZBXNEXT-2717
